name: Hola Mundo

# on: [push, pull_request]
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: My Action
        uses: ./.github/actions/my-action
      # - name: LS
      #   run: ls -al
      # - name: Set up Node.js
      #   uses: actions/setup-node@v4.0.4
      # - name: Node version
      #   run: node --version

      # - name: Run script
      #   run: |
      #     chmod +x script.sh
      #     ./script.sh

  # hola:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Hola Mundo
  #       run: echo 'Hola Mundo'
  #     - name: Touch File
  #       run: touch hola.txt
  #     - name: Set tex
  #       run: echo 'Hola Mundo desde txt' > hola.txt
  #     - name: Read text
  #       run: cat hola.txt
  # other:
  #   runs-on: ubuntu-latest
  #   needs: hola
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4.1.7
  #     - name: LS
  #       run: ls -al
