name: Hola Mundo

# on: [push, pull_request]
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  hola:
    runs-on: ubuntu-latest
    steps:
      - name: Hola Mundo
        run: echo 'Hola Mundo'
      - name: Touch File
        run: touch hola.txt
      - name: Set tex
        run: echo 'Hola Mundo desde txt' > hola.txt
      - name: Read text
        run: cat hola.txt
  other:
    runs-on: ubuntu-latest
    needs: hola
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: LS
        run: ls -al
